name = "tvbox-aggregator"
main = "src/cf-entry.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

routes = [
{ pattern = "leexuben.qzz.io/*", zone_id = "fc52331753ebceb05bed347d63593f6d" }
]

[triggers]
crons = ["0 * * * *"]

[[kv_namespaces]]
binding = "KV"
id = "1d7c37e819434fa9922057310a41f989"
preview_id = "ba0ba8b5866c4ac3a06efcd4df209627"

[vars]
SPEED_TIMEOUT_MS = "5000"
SITE_TIMEOUT_MS = "3000"
FETCH_TIMEOUT_MS = "5000"
WORKER_BASE_URL = "https://leexuben.qzz.io"
